name: CD
on:
  push:
    tags: ["v*"]
  release:
    types: [published]
jobs:
  build:
    name: Build
    uses: andrewscwei/workflows/.github/workflows/node-build.yml@v1
    with:
      artifacts-path: lib/
  deploy-npm:
    name: Deploy
    uses: andrewscwei/workflows/.github/workflows/npm-deploy.yml@v1
    needs: [build]
    with:
      artifacts-name: ${{ needs.build.outputs.artifacts-name }}
      artifacts-path: ${{ needs.build.outputs.artifacts-path }}
      create-release: true
      predeploy-command: cp -r lib/* .
    secrets:
      npm-auth-token: ${{ secrets.NPM_AUTH }}
  deploy-pages:
    name: Deploy
    uses: andrewscwei/workflows/.github/workflows/gh-pages-deploy.yml@v1
    needs: [build]
    with:
      artifacts-name: ${{ needs.build.outputs.artifacts-name }}
      artifacts-path: ${{ needs.build.outputs.artifacts-path }}
      predeploy-command: npm run pages
  notify:
    name: Notify
    needs: [build, deploy-npm, deploy-pages]
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - uses: andrewscwei/telegram-action@v1
        with:
          success: ${{ needs.build.result == 'success' && needs.deploy-npm.result == 'success' && needs.deploy-pages.result == 'success' }}
          cancelled: ${{ needs.build.result == 'cancelled' || needs.deploy-npm.result == 'cancelled' || needs.deploy-pages.result == 'cancelled' }}
          bot-token: ${{ secrets.TELEGRAM_DEVOPS_BOT_TOKEN }}
          chat-id: ${{ secrets.TELEGRAM_DEVOPS_CHAT_ID }}
