name: CD
on:
  push:
    branches: [master]
concurrency:
  group: deploy
  cancel-in-progress: true
jobs:
  release:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        id: build
        uses: andrewscwei/actions/node-build@v2
        with:
          prebuild-command: npm run unit
      - name: Create release
        env:
          GIT_AUTHOR_NAME: github-actions[bot]
          GIT_AUTHOR_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          GIT_COMMITTER_NAME: github-actions[bot]
          GIT_COMMITTER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_AUTH }}
        run: |
          cp -r lib/* .
          npx semantic-release
      - name: Deploy to GitHub pages
        uses: andrewscwei/actions/gh-pages-deploy@v2
        with:
          cname: ${{ vars.CNAME }}
          predeploy-command: npm run pages
  notify:
    name: Notify
    needs: [release]
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - uses: andrewscwei/telegram-action@v1
        with:
          success: ${{ needs.release.result == 'success' }}
          cancelled: ${{ needs.release.result == 'cancelled' }}
          bot-token: ${{ secrets.TELEGRAM_DEVOPS_BOT_TOKEN }}
          chat-id: ${{ secrets.TELEGRAM_DEVOPS_CHAT_ID }}
