name: CI
on:
  push:
    branches: ['**']
    tags-ignore: ['v[0-9]+.[0-9]+.[0-9]+']

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    container: node:13.12.0
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cache Node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-modules-
      - name: Install NPM dependencies
        run: npm install
      - name: Deploy to GitHub pages
        run: .github/workflows/deploy_to_gh_pages.sh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
